name: parental_gates
description: This package use for Parental Gates for kid game 
version: 0.0.1
homepage: https://github.com/deep260201/parental_gates

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:


